#!/bin/bash -eu
set -x

# x が立ち上がる時に実行するスクリプト群

INTELLI_MOUSE="Microsoft Microsoft 5-Button Mouse with IntelliEye(TM)"
THINKPAD_TRACKPOINT="pointer:Lite-On Technology Corp. ThinkPad USB Keyboard with TrackPoint"

main(){
    date +'=== %D %T ==================================='
    setup_xinput
}

setup_xinput(){
    setup_intelli_mouse
    setup_thinkpad
}

setup_intelli_mouse(){
    xinput_intelli_mouse "Device Accel Profile" 3
    xinput_intelli_mouse "Device Accel Constant Deceleration" 1
    xinput_intelli_mouse "Device Accel Adaptive Deceleration" 3
    xinput_intelli_mouse "Device Accel Velocity Scaling" 2
}

xinput_intelli_mouse(){
    xinput set-prop "$INTELLI_MOUSE" "$1" "$2"
}

setup_thinkpad(){
    xinput_thinkpad_trackpoint "Device Accel Profile" 3
    xinput_thinkpad_trackpoint "Device Accel Constant Deceleration" 1
    xinput_thinkpad_trackpoint "Device Accel Adaptive Deceleration" 10
    xinput_thinkpad_trackpoint "Device Accel Velocity Scaling" 10
}

xinput_thinkpad_trackpoint(){
    xinput set-prop "$THINKPAD_TRACKPOINT" "$1" "$2"
}

main >> ~/.xinput.log
